---
# File: main.yml - Main tasks for Nomad

- name: Include checks/asserts
  ansible.builtin.include_tasks:
    file: asserts.yml

- name: Include OS variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

# -----------------------------------------------------------------------
# Tasks for all *NIX operating systems
# -----------------------------------------------------------------------
- name: Include LINUX tasks
  ansible.builtin.include_tasks:
    file: linux.yml
  when: ansible_os_family != 'Windows'

# -----------------------------------------------------------------------
# Tasks for Windows
# -----------------------------------------------------------------------

- name: Include Windows tasks
  ansible.builtin.include_tasks:
    file: windows.yml
  when: ansible_os_family == 'Windows'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
